version: '3.2'
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '28017:27017'
    volumes:
      - ./data:/data/db

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - '8081:3000'
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    environment:
      - JWT_SECRET=c4VJW6YavdKjhi10ltjF5UTd9utI8qb4

  movie-service:
    build:
      context: ./movie-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./movie-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=c4VJW6YavdKjhi10ltjF5UTd9utI8qb4
      - JWT_ISS=https://www.netguru.com/
      - MONGO_URL=mongodb://mongo:27017/movie-db
      - OMDB_URL=http://www.omdbapi.com
    ports:
      - '8082:3000'
    depends_on:
      - mongo
