version: '3.2'
services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - '8081:3000'
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    environment:
      - JWT_SECRET=c4VJW6YavdKjhi10ltjF5UTd9utI8qb4
