name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: TEST=unit docker-compose -f docker-compose.test.yml -f docker-compose.ci.yml up

      - name: Run e2e tests
        run: TEST=e2e docker-compose -f docker-compose.test.yml -f docker-compose.ci.yml up
